Update to MPlayer SVN rev 33132.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35,6 +35,29 @@
 #
 #############################################################################
 
+if test -e ffmpeg/.svn ; then
+  echo "You have an outdated FFmpeg SVN checkout in ffmpeg/, please (re)move or replace it"
+  exit 1
+fi
+
+if test -e ffmpeg/mp_auto_pull ; then
+  if ! (cd ffmpeg && git pull --rebase --ff-only) ; then
+    echo "git pull failed, (re)move ffmpeg/mp_auto_pull to disable pulling"
+    exit 1
+  fi
+fi
+
+if ! test -e ffmpeg ; then
+  echo "No FFmpeg checkout, press enter to download one with git or CTRL+C to abort"
+  read tmp
+  if ! git clone --depth 1 git://git.videolan.org/ffmpeg.git ffmpeg ; then
+    rm -rf ffmpeg
+    echo "Failed to get a FFmpeg checkout"
+    exit 1
+  fi
+  touch ffmpeg/mp_auto_pull
+fi
+
 # Prevent locale nonsense from breaking basic text processing utils
 export LC_ALL=C
 
@@ -404,10 +427,11 @@ Codecs:
   --disable-liba52          disable liba52 [autodetect]
   --disable-libmpeg2        disable libmpeg2 [autodetect]
   --disable-libmpeg2-internal disable builtin libmpeg2 [autodetect]
-  --disable-musepack        disable musepack support [autodetect]
+  --enable-musepack         enable libmpcdec support (deprecated in favour of libavcodec) [disabled]
   --disable-libopencore_amrnb disable libopencore_amr narrowband [autodetect]
   --disable-libopencore_amrwb disable libopencore_amr wideband [autodetect]
   --disable-libopenjpeg     disable OpenJPEG (JPEG2000) input/output support [autodetect]
+  --disable-crystalhd       disable CrystalHD support [autodetect]
   --disable-decoder=DECODER disable specified FFmpeg decoder
   --enable-decoder=DECODER  enable specified FFmpeg decoder
   --disable-encoder=ENCODER disable specified FFmpeg encoder
@@ -750,6 +774,7 @@ _vidix_pcidb=yes
 _dhahelper=no
 _svgalib_helper=no
 _joystick=no
+crystalhd=auto
 _xvid=auto
 _xvid_lavc=auto
 _x264=auto
@@ -806,7 +831,7 @@ _enca=auto
 _inet6=auto
 _gethostbyname2=auto
 _ftp=auto
-_musepack=auto
+_musepack=no
 _vstream=auto
 _pthreads=auto
 _w32threads=auto
@@ -1194,6 +1219,8 @@ for ac_option do
   --disable-svgalib_helper)     _svgalib_helper=no      ;;
   --enable-joystick)    _joystick=yes   ;;
   --disable-joystick)   _joystick=no    ;;
+  --enable-crystalhd)   crystalhd=yes  ;;
+  --disable-crystalhd)  crystalhd=no   ;;
   --enable-xvid)        _xvid=yes       ;;
   --disable-xvid)       _xvid=no        ;;
   --enable-xvid-lavc)   _xvid_lavc=yes  ;;
@@ -2576,7 +2603,7 @@ else
 fi
 
 cflag_check -mno-omit-leaf-frame-pointer && cflags_no_omit_leaf_frame_pointer="-mno-omit-leaf-frame-pointer"
-cflag_check -MD -MP && DEPFLAGS="-MD -MP $CFLAGS"
+cflag_check -MD -MP && DEPFLAGS="-MD -MP"
 
 
 if test -n "$LDFLAGS" ; then
@@ -2870,7 +2897,7 @@ if arm ; then
     _armv6t2=no
     inline_asm_check '"movt r0, #0"' && _armv6t2=yes
   fi
-  echores "$_armv6"
+  echores "$_armv6t2"
 
   echocheck "ARM VFP"
   if test $_armvfp = "auto" ; then
@@ -3395,6 +3422,14 @@ fi
 echores "$_gethostbyname2"
 
 
+echocheck "sys/poll.h"
+poll_h=no
+def_poll_h='#define HAVE_POLL_H 0'
+header_check sys/poll.h && poll_h=yes &&
+  def_poll_h='#define HAVE_POLL_H 1'
+echores "$poll_h"
+
+
 echocheck "inttypes.h (required)"
 _inttypes=no
 header_check inttypes.h && _inttypes=yes
@@ -3567,7 +3602,7 @@ if test "$_pthreads" = yes ; then
   extra_cflags="$extra_cflags $THREAD_CFLAGS"
 else
   res_comment="v4l, v4l2, ao_nas, win32 loader disabled"
-  def_pthreads='#undef HAVE_PTHREADS'
+  def_pthreads='#define HAVE_PTHREADS 0'
   _nas=no ; _tv_v4l1=no ; _tv_v4l2=no
   mingw32 || _win32dll=no
 fi
@@ -4372,7 +4407,7 @@ if test "$_vdpau" = yes ; then
 else
   def_vdpau='#define CONFIG_VDPAU 0'
   novomodules="vdpau $novomodules"
-  libavdecoders=$(echo $libavdecoders | sed -e s/MPEG_VDPAU_DECODER// -e s/MPEG1_VDPAU_DECODER// -e s/H264_VDPAU_DECODER// -e s/WMV3_VDPAU_DECODER// -e s/VC1_VDPAU_DECODER// -e s/MPEG4_VDPAU_DECODER//)
+  libavdecoders=$(echo $libavdecoders | sed -e 's/[A-Z0-9]*_VDPAU_DECODER//g')
 fi
 echores "$_vdpau"
 
@@ -6264,7 +6299,9 @@ elif test "$_tremor" = auto; then
 fi
 if test "$_libvorbis" = auto; then
   _libvorbis=no
-  statement_check vorbis/codec.h 'vorbis_packet_blocksize(0, 0)' -lvorbis -logg $_ld_lm && _libvorbis=yes
+  for vorbislibs in '-lvorbis -logg' '-lvorbis -lvorbisenc -logg' ; do
+    statement_check vorbis/vorbisenc.h 'vorbis_encode_ctl(0, 0, 0)' $vorbislibs $_ld_lm && _libvorbis=yes && break
+  done
 fi
 if test "$_tremor_internal" = yes ; then
   _vorbis=yes
@@ -6288,7 +6325,7 @@ elif test "$_libvorbis" = yes ; then
   def_vorbis='#define CONFIG_OGGVORBIS 1'
   codecmodules="libvorbis $codecmodules"
   res_comment="libvorbis"
-  extra_ldflags="$extra_ldflags -lvorbis -logg"
+  extra_ldflags="$extra_ldflags $vorbislibs"
   libavencoders="$libavencoders LIBVORBIS_ENCODER"
 else
   _vorbis=no
@@ -6503,7 +6540,7 @@ fi
 echores "$_libdca"
 
 echocheck "libmpcdec (musepack, version >= 1.2.1 required)"
-if test "$_musepack" = auto ; then
+if test "$_musepack" = yes ; then
   _musepack=no
   cat > $TMPC << EOF
 #include <stddef.h>
@@ -6831,16 +6868,16 @@ test -d ffmpeg/libavutil ||
   die "MPlayer will not compile without libavutil in the source tree."
 ffmpeg=no
 if test "$ffmpeg_a" = auto ; then
-  test -d ffmpeg/libavcore && ffmpeg_a=yes && ffmpeg=yes && extra_cflags="$extra_cflags -DFF_API_MAX_STREAMS=0"
+  test -d ffmpeg/libavutil && ffmpeg_a=yes && ffmpeg=yes && extra_cflags="$extra_cflags -DFF_API_MAX_STREAMS=0"
 elif test "$ffmpeg_so" = auto ; then
   ffmpeg_so=no
-  if $_pkg_config --exists libavcore ; then
-    inc_ffmpeg=$($_pkg_config --cflags libpostproc libswscale libavformat libavcodec libavutil libavcore)
-    _ld_tmp=$($_pkg_config --libs libpostproc libswscale libavformat libavcodec libavutil libavcore)
-    header_check libavcore/avcore.h $inc_ffmpeg $_ld_tmp &&
+  if $_pkg_config --exists libavutil ; then
+    inc_ffmpeg=$($_pkg_config --cflags libpostproc libswscale libavformat libavcodec libavutil)
+    _ld_tmp=$($_pkg_config --libs libpostproc libswscale libavformat libavcodec libavutil)
+    header_check libavutil/avutil.h $inc_ffmpeg $_ld_tmp &&
       extra_ldflags="$extra_ldflags $_ld_tmp" && ffmpeg_so=yes && ffmpeg=yes
-  elif header_check libavcore/avcore.h -lpostproc -lswscale -lavformat -lavcodec -lavutil -lavcore $_ld_lm ; then
-    extra_ldflags="$extra_ldflags -lpostproc -lswscale -lavformat -lavcodec -lavutil -lavcore"
+  elif header_check libavutil/avutil.h -lpostproc -lswscale -lavformat -lavcodec -lavutil $_ld_lm ; then
+    extra_ldflags="$extra_ldflags -lpostproc -lswscale -lavformat -lavcodec -lavutil"
     ffmpeg_so=yes
     ffmpeg=yes
   fi
@@ -6928,6 +6965,22 @@ else
 fi
 echores "$_libdv"
 
+echocheck "CrystalHD"
+if test "$crystalhd" = auto ; then
+   crystalhd=no
+   statement_check_broken libcrystalhd/bc_dts_types.h libcrystalhd/libcrystalhd_if.h 'DtsGetVersion(0, 0, 0)' -lcrystalhd $_ld_lm && crystalhd=yes
+fi
+
+if test "$crystalhd" = yes ; then
+   extra_ldflags="$extra_ldflags -lcrystalhd"
+   def_crystalhd="#define CONFIG_CRYSTALHD 1"
+   codecmodules="crystalhd $codecmodules"
+else
+   def_crystalhd="#define CONFIG_CRYSTALHD 0"
+   nocodecmodules="crystalhd $nocodecmodules"
+   libavdecoders=$(echo $libavdecoders | sed -e 's/[A-Z0-9]*_CRYSTALHD_DECODER//g')
+fi
+echores "$crystalhd"
 
 echocheck "Xvid"
 if test "$_xvid" = auto ; then
@@ -8127,13 +8180,16 @@ CONFIG_LPC     = yes
 CONFIG_LSP     = yes
 CONFIG_MDCT    = yes
 CONFIG_RDFT    = yes
+CONFIG_SINEWIN = yes
 
 $mak_hardcoded_tables
 $mak_libavcodec_mpegaudio_hp
 !CONFIG_LIBRTMP = $nolibrtmp
 CONFIG_LIBRTMP  = $_librtmp
 
+CONFIG_AC3DSP   = $_mencoder
 CONFIG_BZLIB    = $bzlib
+CONFIG_CRYSTALHD= $crystalhd
 CONFIG_ENCODERS = yes
 CONFIG_GPL      = yes
 CONFIG_MLIB     = $_mlib
@@ -8165,13 +8221,14 @@ EOF
 ff_config_enable () {
 list=$(echo $1 | tr '[a-z]' '[A-Z]')
 item=$(echo $2 | tr '[a-z]' '[A-Z]')
-_nprefix=$3;
+_nprefix=$4;
+_defineprefix=$3;
 test -z "$_nprefix" && _nprefix='CONFIG'
 for part in $list; do
   if $(echo $item | grep -q -E "(^| )$part($| )"); then
-    echo "#define ${_nprefix}_$part 1"
+    echo "${_defineprefix}define ${_nprefix}_$part 1"
   else
-    echo "#define ${_nprefix}_$part 0"
+    echo "${_defineprefix}define ${_nprefix}_$part 0"
   fi
 done
 }
@@ -8315,9 +8372,9 @@ $def_pthread_cache
 $def_ebx_available
 $def_words_endian
 $def_bigendian
-$(ff_config_enable "$arch_all" "$arch" "ARCH")
-$(ff_config_enable "$subarch_all" "$subarch" "ARCH")
-$(ff_config_enable "$cpuexts_all" "$cpuexts" "HAVE")
+$(ff_config_enable "$arch_all" "$arch" "#" "ARCH")
+$(ff_config_enable "$subarch_all" "$subarch" "#" "ARCH")
+$(ff_config_enable "$cpuexts_all" "$cpuexts" "#" "HAVE")
 
 
 /* Blu-ray/DVD/VCD/CD */
@@ -8581,6 +8638,7 @@ $def_mkstemp
 $def_mmap
 $def_network
 $def_pic
+$def_poll_h
 $def_posix_memalign
 $def_pthreads
 $def_round
@@ -8608,7 +8666,6 @@ $def_yasm
 #define HAVE_INLINE_ASM 1
 #define HAVE_ISATTY 0
 #define HAVE_LDBRX 0
-#define HAVE_POLL_H 1
 #define HAVE_PPC4XX 0
 #define HAVE_STRERROR_R 0
 #define HAVE_SYMVER_ASM_LABEL 0
@@ -8640,7 +8697,11 @@ $def_yasm
 #define FFMPEG_CONFIGURATION "--enable-gpl --enable-postproc"
 #define FFMPEG_LICENSE "GPL version 2 or later"
 
+#define LIBAV_CONFIGURATION FFMPEG_CONFIGURATION
+#define LIBAV_LICENSE FFMPEG_LICENSE
+
 /* External libraries used through FFmpeg. */
+$def_crystalhd
 $def_faac_lavc
 $def_libdirac_lavc
 $def_libgsm
@@ -8653,14 +8714,14 @@ $def_mp3lame_lavc
 $def_x264_lavc
 $def_xvid_lavc
 
-$(ff_config_enable "$libavdecoders_all"  "$libavdecoders")
-$(ff_config_enable "$libavencoders_all"  "$libavencoders")
-$(ff_config_enable "$libavparsers_all"   "$libavparsers")
-$(ff_config_enable "$libavdemuxers_all"  "$libavdemuxers")
-$(ff_config_enable "$libavmuxers_all"    "$libavmuxers")
-$(ff_config_enable "$libavprotocols_all" "$libavprotocols")
-$(ff_config_enable "$libavbsfs_all"      "$libavbsfs")
-$(ff_config_enable "$libavhwaccels_all"  "$libavhwaccels")
+$(ff_config_enable "$libavdecoders_all"  "$libavdecoders" "#")
+$(ff_config_enable "$libavencoders_all"  "$libavencoders" "#")
+$(ff_config_enable "$libavparsers_all"   "$libavparsers" "#")
+$(ff_config_enable "$libavdemuxers_all"  "$libavdemuxers" "#")
+$(ff_config_enable "$libavmuxers_all"    "$libavmuxers" "#")
+$(ff_config_enable "$libavprotocols_all" "$libavprotocols" "#")
+$(ff_config_enable "$libavbsfs_all"      "$libavbsfs" "#")
+$(ff_config_enable "$libavhwaccels_all"  "$libavhwaccels" "#")
 
 #endif /* MPLAYER_CONFIG_H */
 EOF
@@ -8692,6 +8753,7 @@ for part in $arch $subarch; do
   part=$(echo $part | tr '[a-z]' '[A-Z]')
   echo "%define ARCH_${part}" >> "$TMPS"
 done
+echo "$(ff_config_enable "$cpuexts_all" "$cpuexts" "%" "HAVE")" >> "$TMPS"
 
 cmp -s "$TMPS" config.asm || mv -f "$TMPS" config.asm
 fi
